application: hat-experience
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/css
  static_dir: static/css

- url: /static/image
  static_dir: static/image

- url: /static/js
  static_dir: static/js

- url: /post
  script: post.app

- url: /test
  script: test.app

- url: /get
  script: get.app

- url: /find
  script: find.app

- url: /tags
  script: tags.app

- url: /
  static_files: static/html/index.html
  upload: static/html/index.html

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: django
  version: "1.2"
